package package.name;
// <- keyword.import

import another.package;
// <- keyword.import

include another.package;
// <- keyword.import

@annotation
// ^ attribute          
class PendingMessageList extends ManagedObject {
// <- keyword.type
//    ^ type
//                       ^ keyword
//                                ^ type

    @dereferenced
    Vector<unsigned long> pendingMessages;
//  ^ type
//         ^ type.builtin
//                  ^ type.builtin

    transient ChatRoomMap roomMap;

    boolean mute;

    @dereferenced
    private transient VectorMap<string, unsigned int> moodTypes;


    public PendingMessageList() {

    }

    @local
    public Vector<unsigned long> getPendingMessages() {
        return pendingMessages;
    }

    public void clearPendingMessages() {
        pendingMessages.removeAll();
    }

    public void addPendingMessage(unsigned long oid) {
        pendingMessages.add(oid);
//                          ^ variable.parameter
    }
}

